### ISSUE TITLE
Failed to get site pages.

### ISSUE THREAD

**Issue by morristai** [HEIGE-PCloud/Notion-Hugo#118]
I followed all the steps inside README, but failed on CD when getting the Notion page content.
Already check:
1. Token already in GitHub Action secret.
2. share link added into the `notion-hugo.config.ts`.
3. add integration into shared page.

(However, I noticed that Notion changed how they share the page with integrated tools, like the picture below, so I added Notion-Hugo to the connection. I don't know if these changes caused the failure.)
![image](https://user-images.githubusercontent.com/10728152/235340554-b1e3aa95-d27d-4e19-a63b-40102459c363.png)

BTW, thanks for the great work! 👍

**Comment by HEIGE-PCloud** [comment]
https://github.com/morristai/Notion-Hugo/actions/runs/4844988107/jobs/8633617001

It seems to fail at the `setup-pages` step... Have you enabled GitHub Pages for your repository?

**Comment by HEIGE-PCloud** [comment]
`GITHUB_TOKEN` is no longer allowed to automatically enable GitHub Pages... I probably need to update the README.

https://github.com/actions/configure-pages/pull/48

**Comment by morristai** [comment]
Thanks @HEIGE-PCloud, sorry for my mistake. Now it's solved and works fine! 👍
