### ISSUE TITLE
用cactus主题, 加载css失败

### ISSUE THREAD

**Issue by LamiaLoveless** [HEIGE-PCloud/Notion-Hugo#128]
一会加载,一会不加载
在cloudflare pages部署

**Comment by HEIGE-PCloud** [comment]
你好，

感谢您联系并报告此问题。为了更好地理解和帮助解决问题，我需要更多信息和[一个最小的可重现示例](https://antfu.me/posts/why-reproductions-are-required-zh)。根据我的初步理解，这个问题可能与Notion-Hugo项目没有直接关系。 我建议尝试以下步骤：

1. 清除浏览器缓存。
2. 检查 Cactus 主题设置并确保一切配置正确。

由于需要更多信息来进一步调查此问题，我将暂时关闭这个 Issue。 但是，请随时重新打开这个 Issue 并提供更多上下文或可重现的示例，我很乐意调查它并帮助您解决任何问题。

此致。
