### ISSUE TITLE
如何给文章添加Front Matter?

### ISSUE THREAD

**Issue by LamiaLoveless** [HEIGE-PCloud/Notion-Hugo#136]

**Comment by HEIGE-PCloud** [comment]
<img width="806" alt="image" src="https://github.com/HEIGE-PCloud/Notion-Hugo/assets/52968553/6ad80988-c184-4d9c-9107-d3c738b506e6">
<img width="532" alt="image" src="https://github.com/HEIGE-PCloud/Notion-Hugo/assets/52968553/76c21c9a-ace2-4557-b804-bec3ed9de262">
添加一个自定义属性即可。
