### ISSUE TITLE
Notion-Hugo does not exist in Connections

### ISSUE THREAD

**Issue by joshuamauldin** [HEIGE-PCloud/Notion-Hugo#143]
I've cloned the template into my workspace, even moved it to the project itself. Neither place lets me find `Notion-Hugo` as a connection. And I did go to `Connections > Add Connections`

Did Notion take this down?

**Comment by HEIGE-PCloud** [comment]
You need to create it yourself. https://github.com/HEIGE-PCloud/Notion-Hugo#create-a-notion-integration
