### ISSUE TITLE
能否实现Notion写好，保存了，自动部署？

### ISSUE THREAD

**Issue by qinjo** [HEIGE-PCloud/Notion-Hugo#154]
请问一下，现阶段是只能在Notion上写好文章，然后自己到Github上的Action中手动部署到网页吗？
还是说我这做法可以，但不是最优解？如果有，麻烦告知一声！谢谢！
目前我也在寻找一个更好的自动部署方法，希望大家可以交流一下！

**Comment by HEIGE-PCloud** [comment]
目前是定时部署，默认是每小时部署一次。
