### ISSUE TITLE
Seeking Help in setting up the website correctly.

### ISSUE THREAD

**Issue by nabil6391** [HEIGE-PCloud/Notion-Hugo#157]
http://nabil6391.github.io/nabilmh.hugo/

I have tried to follow the steps but the UI does not look the same as the website. 

Requesting your help if possible as I think you have made very nice instructions to follow. 

This is my repo:https://github.com/nabil6391/nabilmh.hugo

**Comment by HEIGE-PCloud** [comment]
https://github.com/nabil6391/nabilmh.hugo/blob/25245854522f7561f73a7846035742fea1465ef4/config/_default/config.toml#L1C3-L1C3

You set your baseURL incorrectly. 
See: https://gohugo.io/getting-started/configuration/#baseurl
It should be `http://nabil6391.github.io/nabilmh.hugo/`
