### ISSUE TITLE
Hyperlinks not working when displayed on website

### ISSUE THREAD

**Issue by joecatarata** [HEIGE-PCloud/Notion-Hugo#173]
Hello, the hyperlinks are not showing properly when deployed to a website, may I know a workaround / fix for this if any? Thanks a bunch!

**Comment by HEIGE-PCloud** [comment]
Are you using the latest Notion-Hugo, or can you provide an example website/demo so I can look into this. Thanks.

The inline link is not broken on the example site though. https://notionhugo.pcloud.dev/posts/markdown/#heading-2

**Comment by HEIGE-PCloud** [comment]
Yes, this was reported back in August and a fix was implemented at https://github.com/HEIGE-PCloud/Notion-To-Markdown/commit/ff751fa25e7e3bfad964a7e6db42ea2ea7797ce6

To upgrade, override `package.json`, `package-lock.json` file  and the `src` folder with the latest one in this repository should do.

**Comment by HEIGE-PCloud** [comment]
For the image, the image links provided by Notion API expires after 1 hour. So the easiest way to get around that is to auto build your website every hour or so. I think Hugo has the capability to cache remote images, which is the most elegant solution, but I don't think all themes support it.

See: https://github.com/HEIGE-PCloud/DoIt/pull/860

**Comment by joecatarata** [comment]
Thank you! Will try those out

**Comment by joecatarata** [comment]
Hyperlinks seem to be working as intended, thanks so much!
