### ISSUE TITLE
Bold and Italicized fonts not showing properly

### ISSUE THREAD

**Issue by joecatarata** [HEIGE-PCloud/Notion-Hugo#174]
![image](https://github.com/HEIGE-PCloud/Notion-Hugo/assets/23512969/a6684080-100f-4313-8d44-02fbaeee5dbc)

Hi! I'm not sure if this is a theme issue but I noticed that when a whitespace is present in a bold/italicized word, it shows up as raw markdown as shown on the image above.

**Comment by joecatarata** [comment]
Unrelated question but is there a way to resize images as scaled in Notion?

**Comment by HEIGE-PCloud** [comment]
I believe this is expected in Markdown, GitHub does not render this as bold as well.

**/tiny **

> Unrelated question but is there a way to resize images as scaled in Notion?

No, Notion Public API does not provide any size information about the images, so it is not possible currently.  https://developers.notion.com/reference/block#image

**Comment by joecatarata** [comment]
Alright, thank you!
