### ISSUE TITLE
Problem with published website

### ISSUE THREAD

**Issue by spark-your-heart-ablaze** [HEIGE-PCloud/Notion-Hugo#230]
Hello. 

Not working for me. The website is unformatted after publishing. What can be a problem? Completed all the steps including the changing the base url in config.toml.
https://github.com/spark-your-heart-ablaze/notion-blog/actions
Link to repo
![Screenshot (13)](https://github.com/HEIGE-PCloud/Notion-Hugo/assets/18232879/20836f43-37e6-4fc0-948c-572ce58098e7)

**Comment by HEIGE-PCloud** [comment]
Long story short - change https://github.com/spark-your-heart-ablaze/notion-blog/blob/main/config/DoIt/config.toml#L1C12-L1C38 to https://spark-your-heart-ablaze.github.io/notion-blog/

---

Full story

The default theme is the gohugo-theme-ananke which recently introduce a serious bug that prevents the site from building https://github.com/theNewDynamic/gohugo-theme-ananke/pull/685 so I switched the environment variable to the DoIt theme https://github.com/HEIGE-PCloud/Notion-Hugo/blob/main/.github/workflows/cd.yml#L67 Hugo environment also affects how the config is picked so only configurations under https://github.com/HEIGE-PCloud/Notion-Hugo/tree/main/config/DoIt will be active.

**Comment by spark-your-heart-ablaze** [comment]
Thank you for your work! Project is awesome
