### ISSUE TITLE
Cant find integration user — results in build failed

### ISSUE THREAD

**Issue by VitalyKrenel** [HEIGE-PCloud/Notion-Hugo#236]
<img width="1191" alt="image" src="https://github.com/HEIGE-PCloud/Notion-Hugo/assets/17354709/4ae73545-0f36-4c80-ac18-235e9d8a4d5d">

I use Telegram to Notion bot to add posts to my database. The Telegram to Notion is connect as Notion Integration. For some reason `notion.users.retrieve()` cannot find integration user. 

Unfortunately, Telegram to Notion does not have a "user" I could invite as guest to the database. 

For the time being, I workarounded this way:
1. Add field "authors" to the database — case is important.
2. Add automation to Notion database: when page is added, specify your user as 'authors'

**Comment by HEIGE-PCloud** [comment]
Well, this seems to be a limitation of Notion's API and there isn't much we can do about it.

https://developers.notion.com/reference/user#bots

It does support querying of bot's information, but I guess it only works when querying about the bot itself.
