### ISSUE TITLE
Build with hugo 出现错误

### ISSUE THREAD

**Issue by soslane** [HEIGE-PCloud/Notion-Hugo#238]
![image](https://github.com/HEIGE-PCloud/Notion-Hugo/assets/149466045/50429048-8ba6-4c4f-a21f-61610bc80807)

麻烦问下如何解决？我是按照你的ReadME文档进行部署的。但是出现了以上错误。
错误提示是在工作区没找到用户，这是否跟我的notion是education plus版有关呢？因为这个版的notion是无法在work space里创建用户的。但是我使用了普通版本的notion，也是出现同样的提示。

**Comment by HEIGE-PCloud** [comment]
应该是 #236

**Comment by HEIGE-PCloud** [comment]
我哪天应该把 Notion-To-Markdown 和这个项目合并了。修了一边忘了另一边。

**Comment by HEIGE-PCloud** [comment]
@soslane 现在应该没问题了，更新试试。
