### ISSUE TITLE
Hello, I want to import previous articles, but I found that there is no place to modify the article time. Can you help me check this problem? Thank you very much!

### ISSUE THREAD

**Issue by fidjiw** [HEIGE-PCloud/Notion-Hugo#252]
Hello, I want to import previous articles, but I found that there is no place to modify the article time. Can you help me check this problem? Thank you very much!

**Comment by HEIGE-PCloud** [comment]
The time is fetched from Notion’s created time and edited time. There is no way to edit them directly on Notion, so you probably need to be creative.
