### ISSUE TITLE
Action failed with error Unexpected HTTP response: 404

### ISSUE THREAD

**Issue by aric6494** [HEIGE-PCloud/Notion-Hugo#276]
![Snipaste_2024-12-15_11-28-37](https://github.com/user-attachments/assets/2f902572-b15e-4577-ab28-c6f1840d29de)
前几天我跟着你的readme文档部署完成后可以正常使用，但是今天上午发现了这个错误，请问要如何解决

**Comment by HEIGE-PCloud** [comment]
https://github.com/peaceiris/actions-hugo/issues/652

Try a lower `hugo_version`

**Comment by ALF-eV** [comment]
Using 0.139.4 is a manual solution for pipelines currently using `latest` we'll have to remember to revert later on. Not ideal. Is it hard to add the missing assets?

**Comment by aric6494** [comment]
Thanks,i solved it
