### ISSUE TITLE
Bug when using it with the theme Stack

### ISSUE THREAD

**Issue by sysfox** [HEIGE-PCloud/Notion-Hugo#99]
Sorry to bother you.
I used your project today , It is useful.
However , everything goes well except one :

**The article is rendered and it has its own link , tag , and category, but isn't shown on the home page!**

Please help me.

My repo: https://github.com/sysfox/Diary
My Site: https://diary.trfox.ml
The rendered article: https://diary.trfox.ml/posts/20230129/
Theme: stack (latest)

**Comment by HEIGE-PCloud** [comment]
Change this line

https://github.com/sysfox/Diary/blob/c05d87f38cc9375b6b061df2534a567a33dccd7d/config.yaml#L34

to 

```yaml
    posts: /posts/:slug/
```

**Comment by sysfox** [comment]
Thanks for help

**Comment by xingfanxia** [comment]
> Sorry to bother you. I used your project today , It is useful. However , everything goes well except one :
> 
> **The article is rendered and it has its own link , tag , and category, but isn't shown on the home page!**
> 
> Please help me.
> 
> My repo: https://github.com/sysfox/Diary My Site: https://diary.trfox.ml The rendered article: https://diary.trfox.ml/posts/20230129/ Theme: stack (latest)

Hi having the same problem but the links are not available any more..
